# Generated by Django 3.2 on 2021-04-14 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_auto_20210414_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='owner',
        ),
    ]
